on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.0.0'

name: Create New Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install npm
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: increment package version
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: CI release script
          author_email: ci@automate.bot
          message: "Version increment to: ${{ github.event.inputs.version }}"
          add: "package*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}              
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release v${{ github.event.inputs.version }}
          body: |
            Official version release
          draft: false
          prerelease: false
